version: '3.5'
services:

  squid:
    image: shoepping/squid:19.04.14
    ports:
      - "3128:3128"
    restart: always
    volumes:
      - squid-data:/var/spool/squid

volumes:
  squid-data:
    name: squid-data-volume

